version: "3.8"
services:
  triple_be_homework_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
      - kafka
    ports:
      - "8080:8080"
  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3307:3307"
    env_file:
      - env/mysql.env
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
